# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af98ca71e7db40d715cfd784c77a656f2ff6377518299307fa1df7db8faa7c6921eea4547191321abaf0c0b169282cc7cdab5701c695aeb8f8a613c26ff4116c

test:
  secret_key_base: 620b0c1d5276d6e308b3b28265bac80239b6510c9c2e8552b0c74a0fa1d4dee56583e7b0f0120ace4237ce4f15f2d5cba163d1ceedd582cfee40ee9b0e9db6db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
